theme: jekyll-theme-hacker

title: kvark's ideas blog
description: >-
  Trying to make sense of the world.

baseurl: "/"
url: "https://kvark.github.io/ideas"

permalink: /:title

author:
  name: "kvark"
  email: "kvark at fastmail com"
  url: "https://kvark.github.io/ideas"
